Add first React test to call center
team-telnyx/telnyx-client-examples pull request #38
Opened 2020-10-07 19:31 UTC by SuaYoo

Describe your changes

## ✋ Manual testing

1. Provide manual testing instructions

## 🦊 Browser testing

### Desktop
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### Mobile
- [ ] Chrome (Android)
- [ ] Safari (iOS)

## 📸 Screenshots

2020-10-07 19:34 UTC, SuaYoo commented on call-center/web-client/__mocks__/@telnyx/webrtc.ts
> +class TelnyxRTC {
This would be nice to include in the SDK in the future.

2020-10-07 19:34 UTC, SuaYoo commented on call-center/web-client/package.json
> +    "@testing-library/react": "^10.4.9",
Had to upgrade and add `jest-environment-jsdom-sixteen` to use `waitFor`, see linked issues.

2020-10-07 19:35 UTC, SuaYoo commented on call-center/web-client/src/__tests__/helpers/createWebRTCCall.ts
> +  localStream: new MediaStream(),
This change snuck in since it started to throw a type error.

2020-10-07 19:35 UTC, SuaYoo commented on call-center/web-client/tsconfig.json
> +    "lib": ["dom", "dom.iterable", "esnext"],
Looks like some formatting change was committed here, too

2020-10-08 13:49 UTC, DeividVeloso requested changes
The test failed to me 
![image](https://user-images.githubusercontent.com/16343871/95467458-dc6d0580-0953-11eb-99a3-afe2b4488f9a.png)

2020-10-08 16:07 UTC, SuaYoo commented
> The test failed to me
> ![image](https://user-images.githubusercontent.com/16343871/95467458-dc6d0580-0953-11eb-99a3-afe2b4488f9a.png)

@DeividVeloso can you run `npm install` in `call-center/web-client` and try again? Forgot to mention that in the description.

2020-10-08 16:23 UTC, DeividVeloso approved these changes

2020-10-08 16:29 UTC, merged