feat(WEBRTC-176): Add a quickstart on README
team-telnyx/telnyx-client-examples pull request #41
Opened 2020-10-08 17:42 UTC by DeividVeloso

Create steps with how to set up a call center app

## ✋ Manual testing

1. Review the content 
2. See the preview mode.

## 🦊 Browser testing

### Desktop
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### Mobile
- [ ] Chrome (Android)
- [ ] Safari (iOS)

## 📸 Screenshots
![image](https://user-images.githubusercontent.com/16343871/95494533-717ff680-0974-11eb-95d1-c469e663cbc8.png)

2020-10-08 18:01 UTC, DeividVeloso commented on call-center/README.md
> +![buy a phone number](https://raw.githubusercontent.com/team-telnyx/telnyx-client-examples/WEBRTC-176/call-center/screenshots/buy_phone_number.png)
Before the merge, we need to change all places that are using in the URL images from `WEBRTC-176/` to `main`

2020-10-08 21:16 UTC, SuaYoo commented on call-center/README.md
> +![buy a phone number](https://raw.githubusercontent.com/team-telnyx/telnyx-client-examples/WEBRTC-176/call-center/screenshots/buy_phone_number.png)
You can use relative paths here: `screenshots/buy_phone_number.png`

2020-10-08 21:30 UTC, SuaYoo requested changes
General suggestions:
- It looks like there's an extra backslash at the end of some lines, ex: `sign up for your free Telnyx account.\`
- Switch to relative file paths for all screenshots

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +This is an example of a call center app. You can use to manage, make and receive calls, create call conferences and control the agents.
Suggested wording tweak:
```suggestion
This is an example of a call center app that uses the Telnyx Client and Call Control SDKs. You can make and receive phone calls in the browser, create call conferences, and manage call center agents.
```

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +In this guide, you’ll learn how to get started with Call Center App using Call Control and Telnyx Portal. Just follow these steps:
```suggestion
In this guide, you’ll learn how to get started with the Call Center App by using Telnyx SDKs and the Telnyx Portal. Just follow these steps:
```

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +1. Sign up for a Telnyx Account.
```suggestion
1. Sign up for a Telnyx Account
```

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +6. Create a SIP connection
```suggestion
6. Create a SIP Connection
```

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +You will need it to be able to receive websocket request from Call Control App
```suggestion
You will need it to be able to receive websocket requests from the Call Control App 
```

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +1. Run `npm install`
```suggestion
1. Run `npm install` from the `call-center` folder
```

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +3. Open the ngrok Web Interface (ex: <http://127.0.0.1:4040/inspect/http>). You should see `/login` request.
```suggestion
3. Log in as a call center agent in the browser. Open the ngrok Web Interface (ex: <http://127.0.0.1:4040/inspect/http>) in a separate tab. You should see `/login` request.
```

2020-10-08 21:30 UTC, SuaYoo commented on call-center/README.md
> +4. Call your Call Center phone number from your personal device or a web dialer. You should see requests to `POST /calls/callbacks/call-control-app` come through. (Note: Events may not show up in the
```suggestion
4. Call your Call Center phone number from your personal device or a web dialer. You should see requests to `POST /calls/callbacks/call-control-app` come through.
```

2020-10-09 12:59 UTC, DeividVeloso commented
> General suggestions:
> 
> * It looks like there's an extra backslash at the end of some lines, ex: `sign up for your free Telnyx account.\`
> * Switch to relative file paths for all screenshots

I put the backslash to do a new line.

2020-10-09 17:18 UTC, SuaYoo commented
> I put the backslash to do a new line.

It doesn't look like this is supported in all markdown processors (in fact, the VSCode default preview still shows backslashes.) Can you replace with two spaces? See: https://www.markdownguide.org/basic-syntax/#line-break-best-practices

2020-10-16 16:56 UTC, SuaYoo approved these changes

2020-10-19 21:10 UTC, merged