Dial using call control
team-telnyx/telnyx-client-examples pull request #51
Opened 2020-10-16 21:00 UTC by SuaYoo

Describe your changes

## ✋ Manual testing

1. Provide manual testing instructions

## 🦊 Browser testing

### Desktop
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### Mobile
- [ ] Chrome (Android)
- [ ] Safari (iOS)

## 📸 Screenshots

2020-10-19 18:25 UTC, hugobdev requested changes
Minor changes requested, looks good overall

2020-10-19 18:25 UTC, hugobdev commented on call-center/server/controllers/calls.controller.ts
> +  // initiation UUID, which tells the server create a conference call
This changed

2020-10-19 18:25 UTC, hugobdev commented on call-center/web-client/package-lock.json
> +        }
I believe you are not using this anymore

2020-10-19 18:38 UTC, SuaYoo commented on call-center/server/controllers/calls.controller.ts
> +  // initiation UUID, which tells the server create a conference call
Good catch

2020-10-19 18:39 UTC, SuaYoo commented on call-center/web-client/package-lock.json
> +        }
This is a dependency of another package, it's been removed from `package.json`

2020-10-19 20:21 UTC, SuaYoo commented on call-center/server/controllers/calls.controller.ts
> +  public static get = async function (req: Request, res: Response) {
This is a generic GET method, I could probably have moved this to another PR.

2020-10-19 20:24 UTC, SuaYoo commented on call-center/web-client/src/components/Common/index.tsx
> +  let [isDialInitiated, setIsDialInitiated] = useState<boolean>(false);
The `isDialInitiated` check can likely be removed once https://github.com/team-telnyx/webrtc/pull/46 is published.

2020-10-21 20:42 UTC, hugobdev approved these changes
Looks great, minor comment

2020-10-21 20:42 UTC, hugobdev commented on call-center/web-client/src/components/Common/index.tsx
> +    telnyxClient.on('telnyx.notification', async (notification: any) => {
It doesn't look like you use any `await` inside.

2020-10-21 20:57 UTC, merged