Use Call Control ID to identify invite & transfer
team-telnyx/telnyx-client-examples pull request #54
Opened 2020-10-21 21:41 UTC by SuaYoo

Uses Telnyx CC ID to identify a call when inviting someone to a conference or transferring a call.

## ✋ Manual testing

1. Run call-center app and log in as multiple agents
2. Call your call center app
3. Transfer the call to an agent. Verify that agent receives and can answer call
4. Add the other agent to the conference call. Verify that the other agent receives & can answer
6. Hang up and repeat for with an outbound call

## 🦊 Browser testing

### Desktop
- [ ] Edge
- [ ] Chrome
- [x] Firefox
- [ ] Safari

### Mobile
- [ ] Chrome (Android)
- [ ] Safari (iOS)

## 📸 Screenshots

2020-10-21 21:41 UTC, SuaYoo commented on call-center/server/controllers/calls.controller.ts
> -  public static bridge = async function (req: Request, res: Response) {
Minor refactor to remove unused call action

2020-10-22 12:01 UTC, DeividVeloso approved these changes

2020-10-22 12:21 UTC, DeividVeloso requested changes
I tried to make a call and it is not working 

![image](https://user-images.githubusercontent.com/16343871/96870872-e7da2980-1447-11eb-82f6-5330d946fb5c.png)

2020-10-22 15:53 UTC, SuaYoo commented
@DeividVeloso what version of @telnyx/webrtc do you have locally? It should be 2.2.0. Can you run `npm install` and try testing again?

2020-10-22 15:58 UTC, hugobdev approved these changes
Great refactor

2020-10-22 17:38 UTC, DeividVeloso approved these changes

2020-10-22 17:58 UTC, merged