feat(WEBRTC-198):  merge Common component with App and create hook telnyxRTC
team-telnyx/telnyx-client-examples pull request #62
Opened 2020-10-29 17:34 UTC by DeividVeloso

- merge Common component with App 
 - create hook telnyxRTC

## ✋ Manual testing

1. Provide manual testing instructions

## 🦊 Browser testing

### Desktop
- [ ] Edge
- [x] Chrome
- [ ] Firefox
- [ ] Safari

2020-10-29 20:47 UTC, SuaYoo requested changes

2020-10-29 20:47 UTC, SuaYoo commented on call-center/web-client/src/hooks/useTelnyxRTC.ts
> +) {
IMO it would be easier to understand the call signature if there was only one argument, you could set up an interface too:
```suggestion
interface IUseTelnyxRTCParams {
  agentId: string | undefined;
  token: string | undefined;
  clearDialingDestination: any;
}

function useTelnyxRTC({
  agentId,
  token,
  clearDialingDestination,
}: IUseTelnyxRTCParams) {
```

2020-10-29 20:47 UTC, SuaYoo commented on call-center/web-client/src/hooks/useTelnyxRTC.ts
> +          }
Setting/clearing destination value is not a concern of this hook, so I would leave this out of here.
```suggestion
          }
```

2020-10-29 20:47 UTC, SuaYoo commented on call-center/web-client/src/App.tsx
> +    setDialingDestination
See previous comments, I would check the WebRTC call `"active"` state in `useEffect` in the `App` component, instead of coupling `setDialingDestination` with the hook.

2020-10-29 20:49 UTC, SuaYoo commented
What was behind the decision to move every interface to its own file?

2020-10-30 11:59 UTC, DeividVeloso commented
> What was behind the decision to move every interface to its own file?

I thought to do that because of the organization and the re-use if necessary.

2020-10-30 12:22 UTC, DeividVeloso commented on call-center/web-client/src/hooks/useTelnyxRTC.ts
> +) {
Good idea, done!

2020-10-30 12:22 UTC, DeividVeloso commented on call-center/web-client/src/hooks/useTelnyxRTC.ts
> +          }
Good idea, done!

2020-10-30 12:22 UTC, DeividVeloso commented on call-center/web-client/src/App.tsx
> +    setDialingDestination
Done!

2020-10-30 19:10 UTC, SuaYoo approved these changes
LGTM

2020-10-30 19:55 UTC, merged