Update server logger
team-telnyx/telnyx-client-examples pull request #67
Opened 2020-11-04 22:43 UTC by SuaYoo

Updates logging to use [winston](https://github.com/winstonjs/winston) + [morgan](https://github.com/expressjs/morgan) and silenced TypeORM info logging for more readable logs.

## ✋ Manual testing

Run call-center app and perform a few app functions. Verify that call control events are logged to your terminal.

## 📸 Screenshots

Webhook event logging:
<img width="868" alt="Screen Shot 2020-11-04 at 2 24 37 PM" src="https://user-images.githubusercontent.com/4672952/98175571-af0c6c80-1eab-11eb-8851-801f1bdfa7c2.png">

Error logging:
<img width="868" alt="Screen Shot 2020-11-04 at 2 24 37 PM" src="https://user-images.githubusercontent.com/4672952/98175766-132f3080-1eac-11eb-8128-640b83ac767d.png">

2020-11-04 22:45 UTC, SuaYoo commented on call-center/server/README.md
> +## Production
Noticed we don't talk about environments in the README while working on logging levels

2020-11-04 22:45 UTC, SuaYoo commented on call-center/server/controllers/agents.controller.ts
> +      logger.debug('Error details:', e);
Makes sense as `logger.warn` as well, thoughts?

2020-11-04 22:45 UTC, SuaYoo commented on call-center/server/controllers/callControl.controller.ts
> +        'Webhook received | Event type: %s\nEvent payload: %O',
Open to suggestions on format

2020-11-04 22:45 UTC, SuaYoo commented on call-center/server/controllers/callControl.controller.ts
> +          client_state: clientState,
Does it bother anyone to show the parsed client state?

2020-11-05 14:42 UTC, DeividVeloso requested changes
it is looking good to me, but I think maybe we can change the logger methods using this link
https://github.com/winstonjs/winston#using-logging-levels

2020-11-05 14:42 UTC, DeividVeloso commented on call-center/server/controllers/agents.controller.ts
> +      logger.debug('Error details:', e);
I think that is better to use `logger.error("127.0.0.1 - there's no place like home");` , because is inside the **catch block**

https://github.com/winstonjs/winston#using-logging-levels

2020-11-05 14:42 UTC, DeividVeloso commented on call-center/server/controllers/callControl.controller.ts
> +        'Webhook received | Event type: %s\nEvent payload: %O',
Maybe use one of the methods below instead of `debug`?

```
logger.info("127.0.0.1 - there's no place like home");
logger.warn("127.0.0.1 - there's no place like home");
```

2020-11-05 14:42 UTC, DeividVeloso commented on call-center/server/controllers/callControl.controller.ts
> +          client_state: clientState,
It is good to me

2020-11-05 14:42 UTC, DeividVeloso commented on call-center/server/server.ts
> +    logger.debug(
Maybe use this `logger.info("127.0.0.1 - there's no place like home");`

2020-11-05 18:08 UTC, SuaYoo commented on call-center/server/controllers/agents.controller.ts
> +      logger.debug('Error details:', e);
Capturing convo from Zoom: The try-catch block is used here as a sort of catch-all for the HTTP response, so as written it's not a critical application error. Will go with `logger.warn`

2020-11-06 17:02 UTC, merged